### ISSUE TITLE
arm64 not supported?

### ISSUE THREAD

**Issue by atreidesend** [joke/asdf-chezmoi#1]
https://github.com/joke/asdf-chezmoi/blob/6ccba042bcc485d8960fcc49ca2b3e85d309e14a/lib/utils.bash#L47

Any reason `arm64` is not included in the set that evaluates to arm64?

spent a while this evening trying to figure out why asdf wouldn't install chezmoi properly on a new m1 mbp, and as far as I can tell it's b/c this spits out unsupported architecture, which then gets swallowed up by some layers of the scripting and asdf install process

if I edit the line to include `arm64`, the asdf install process, and chezmoi, _just works_

**Comment by joke** [comment]
@atreidesend Thanks for reporting the bug. It was an oversight.

**Comment by atreidesend** [comment]
awesome, thanks!
