### ISSUE TITLE
Github Release not found at Alpine based Container

### ISSUE THREAD

**Issue by nolte** [joke/asdf-chezmoi#39]
### Used Release

**Container:** [alpine:latest](https://hub.docker.com/_/alpine)
**asdf plugin:** [v1.0.2](https://github.com/joke/asdf-chezmoi/releases/tag/v1.0.2)
**chezmoi version:** 2.40.0

### Panic Output

```sh
...
* Downloading chezmoi release 2.40.0...
  curl: (22) The requested URL returned error: 404
  asdf-chezmoi: Could not download https://github.com/twpayne/chezmoi/releases/download/v2.40.0/chezmoi_2.40.0_linux_amd64-musl.tar.gz
  FAILED: install exited with an error
```
full log at https://github.com/nolte/asdf-chezmoi/actions/runs/6302247241/job/17109025400

### Expected Behavior

The `asdf plugin` will be load the Release archive from some existing endpoint, for Alpine with some asset name  like `chezmoi_2.40.0_linux-musl_amd64.tar.gz`.

### Actual Behavior

The Plugin looks for some not existing file `chezmoi_2.40.0_linux_amd64-musl.tar.gz`

| **Actual**   | [`chezmoi_2.40.0_linux_amd64-musl.tar.gz`](https://github.com/twpayne/chezmoi/releases/download/v2.40.0/chezmoi_2.40.0_linux_amd64-musl.tar.gz) |
|--------------|------------------------------------------|
| **Expected** | [`chezmoi`_2.40.0_linux-musl_amd64.tar.gz]( https://github.com/twpayne/chezmoi/releases/download/v2.40.0/chezmoi_2.40.0_linux-musl_amd64.tar.gz) |

### Steps to Reproduce

Use the plugin inside a `alpine` based container build, or as [GitHub Action](https://github.com/nolte/asdf-chezmoi/blob/develop/.github/workflows/build.yml#L32)

### References

* https://github.com/joke/asdf-chezmoi/issues/34

**Comment by joke** [comment]
@nolte thanks for reporting the issue. the problem should be fixed now.
